### ISSUE TITLE
Steemit renders any links to IPFS content as an image

### ISSUE THREAD

**Issue by arhag** [steemit/condenser#14]
I was trying to include a link to an IPFS file (not an image). Steemit.com forces it to be an image even when I have the raw link by itself or use the Markdown syntax for a link (not an image).

See [this post](https://steemit.com/steem/@arhag/re-arhag-compiling-steem-for-windows-on-linux-host-20160522t181037082z) for an example.

**Comment by jcalfee** [comment]
A temp fix is in-place.  Because you included your ipfs link in markdown (a code block it appears) it will not turn it into an image.  So you post looks fine to me now.  The next step is to turn this image replacement off completely, this requires the editor to accept a picture in its UI so the non-markdown user can easily include the image.  Please re-open if you see something I missed.

**Comment by arhag** [comment]
No, it is still broken. The IPFS link in the code block was there to work around the fact that the actual Markdown link incorrectly shows up as a broken image (it still does by the way),

Reload the page and then press stop so that the broken image appears. It is between  "... zip file available at" and "for anyone ..."

**Comment by jcalfee** [comment]
I see.. Can you put it in backticks for now?  We are working on the editor design which should fix this.

**Comment by pjau-steem** [comment]
This is still happening https://steemit.com/history/@cheetah/cheetah-re-jbtsphotosthe-beauty-of-mayoyao-ifugao

![ipfs](https://user-images.githubusercontent.com/12845422/57238310-0284cc80-7021-11e9-9937-d01e150fd224.PNG)

This is the body of the post:

> Hi! I am a robot. I just upvoted you! I found similar content that readers might be interested in:
https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Mayoyao%2C_Ifugao.html
